TomaszKusy\En\ProduktyInKartaType:
    properties:
        produktInKarta:
            expose: true
            access_type: public_method
            serialized_name: produktInKarta
            accessor:
                getter: getProduktInKarta
                setter: setProduktInKarta
            xml_list:
                inline: true
                entry_name: produktInKarta
            type: array<TomaszKusy\En\ProduktInKartaType>
